name: AVR Blink

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: acrandal/arduino-cli:latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        apk install make
        cd Blink
        make
